export type Candidate = { name: string; npmName?: string | null; repositoryUrl?: string | null; homepageUrl?: string | null; description: string; keywords: string[]; githubStars?: number | null; npmDownloads?: number | null; latestVersion?: string | null; repositoryUpdatedAt?: string | null; releasedAt?: string | null; archived?: boolean; isSeed?: boolean };
export const NO_DESCRIPTION = "No description provided.";
// npm and package.json store repositories in several git forms (git+https://, git+ssh://git@, git@host:, github:owner/repo, owner/repo).
export function canonicalRepositoryUrl(value: string | null | undefined): string | null { if (!value) return null; let normalized = value.trim(); if (/^github:/i.test(normalized)) normalized = `https://github.com/${normalized.slice(7)}`; else if (/^[\w-]+\/[\w.-]+$/.test(normalized)) normalized = `https://github.com/${normalized}`; normalized = normalized.replace(/^git@github\.com:/i, "https://github.com/").replace(/^(git\+)?(https?|ssh|git):\/\//i, "https://"); try { const url = new URL(normalized.startsWith("https://") || normalized.startsWith("http://") ? normalized : `https://${normalized}`); if (!/^(www\.)?github\.com$/i.test(url.hostname)) return null; const parts = url.pathname.split("/").filter(Boolean).slice(0, 2); return parts.length === 2 ? `https://github.com/${parts[0].toLowerCase()}/${parts[1].replace(/\.git$/i, "").toLowerCase()}` : null; } catch { return null; } }
export function safeHttpUrl(value: string | null | undefined): string | null { if (!value) return null; try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : null; } catch { return null; } }
function preferenceRank(candidate: Candidate): [number, number, number, number] { const repoName = canonicalRepositoryUrl(candidate.repositoryUrl)?.split("/").pop() ?? null; const npmName = candidate.npmName?.trim().toLowerCase() ?? null; return [candidate.isSeed ? 1 : 0, npmName ? 1 : 0, npmName !== null && npmName === repoName ? 1 : 0, candidate.npmDownloads ?? -1]; }
function isPreferred(a: Candidate, b: Candidate) { const left = preferenceRank(a); const right = preferenceRank(b); for (let index = 0; index < left.length; index += 1) { if (left[index] !== right[index]) return left[index] > right[index]; } return false; }
function fillMissing(primary: Candidate, other: Candidate): Candidate { const merged: Candidate = { ...primary }; for (const key of ["npmName", "repositoryUrl", "homepageUrl", "githubStars", "npmDownloads", "latestVersion", "repositoryUpdatedAt", "releasedAt", "archived"] as const) { if (merged[key] === null || merged[key] === undefined) Object.assign(merged, { [key]: other[key] }); } if (merged.description === NO_DESCRIPTION || !merged.description.trim()) merged.description = other.description; if (!merged.keywords.length) merged.keywords = other.keywords; merged.isSeed = Boolean(primary.isSeed || other.isSeed); return merged; }
// Merges candidates that share an npm name or a canonical repository. The preferred entry (seed, then package named like its repository, then most downloaded) supplies identity; the other entries fill missing signals.
export function deduplicateCandidates(candidates: Candidate[]): Candidate[] { const groups: Candidate[] = []; const index = new Map<string, number>(); for (const candidate of candidates) { const npmKey = candidate.npmName?.trim().toLowerCase(); const repoKey = canonicalRepositoryUrl(candidate.repositoryUrl); const keys = [npmKey ? `npm:${npmKey}` : null, repoKey ? `repo:${repoKey}` : null, !npmKey && !repoKey ? `name:${candidate.name.trim().toLowerCase()}` : null].filter((key): key is string => key !== null); const existing = keys.map((key) => index.get(key)).find((position) => position !== undefined); if (existing === undefined) { keys.forEach((key) => index.set(key, groups.length)); groups.push(candidate); continue; } const current = groups[existing]; groups[existing] = isPreferred(candidate, current) ? fillMissing(candidate, current) : fillMissing(current, candidate); keys.forEach((key) => { if (!index.has(key)) index.set(key, existing); }); } return groups; }
